<a href="https://colab.research.google.com/github/silvia-dev-prog/ai-agents-for-beginners/blob/main/C%C3%B3pia_de_C%C3%B3pia_de_silviamoraes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#instalando wget
%%capture
!pip install -q wget
!mkdir data

In [ ]:
#baixando dados das tabelas dimensão e de fatos


import wget
url ='https://raw.githubusercontent.com/cristinaaguiar/DataMartBISolutions/main/data.csv'
wget.download(url, 'data/data.csv')

url='https://raw.githubusercontent.com/cristinaaguiar/DataMartBISolutions/main/funcionario.csv'
wget.download(url, 'data/funcionario.csv')

url ='https://raw.githubusercontent.com/cristinaaguiar/DataMartBISolutions/main/equipe.csv'
wget.download(url, 'data/equipe.csv')
url='https://raw.githubusercontent.com/cristinaaguiar/DataMartBISolutions/main/cargo.csv'
wget.download(url, 'data/cargo.csv')
url = 'https://raw.githubusercontent.com/cristinaaguiar/DataMartBISolutions/main/cliente.csv'
wget.download(url, 'data/cliente.csv')
url='https://raw.githubusercontent.com/cristinaaguiar/DataMartBISolutions/main/pagamento.csv'
wget.download(url, 'data/pagamento.csv')
url='https://raw.githubusercontent.com/cristinaaguiar/DataMartBISolutions/main/negociacao.csv'
wget.download(url, 'data/negociacao.csv')

'data/negociacao.csv'

In [ ]:
# Instações e inicializações
#instala Java Runtime Environment (JRE) versão 17
%%capture
!apt-get install -y openjdk-8-jdk-headless
!pip install pyspark==3.5.1

In [ ]:
#configurando as variáveis de ambiente
import os
os.environ['JAVA_HOME'] = '/usr/lib/jvm/java-17-openjdk-amd64'

In [ ]:
#fazendo a conexão com Spark
from pyspark.sql import SparkSession
spark = SparkSession.builder\
    .master('local[*]')\
    .appName('ColabSpark')\
    .getOrCreate()

In [ ]:
#bibliotecas necessárias
from pyspark.sql.types import IntegerType
from pyspark.sql.types import FloatType
from pyspark.sql.functions import round, desc


import random
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import tensorflow as tf
from numpy.random import seed
from tensorflow.random import set_seed
from tensorflow import keras
from tensorflow.keras import layers

In [ ]:
#Geração de dataframe em pandas da BI Solutions
pd.set_option('display.float_format', lambda x: '%.2f' % x)

In [ ]:
cargoPandas=pd.read_csv('https://raw.githubusercontent.com/cristinaaguiar/DataMartBISolutions/main/cargo.csv', sep=',')
cargoPandas.head()

,cargoPK,cargoNome,cargoRegimeTrabalho,cargoJornadaTrabalho,cargoEscolaridadeMinima,cargoNivel
0,1,PROGRAMADOR DE SISTEMAS DE INFORMACAO,TEMPORARIO,20H,MEDIO,JUNIOR
1,2,PROGRAMADOR DE SISTEMAS DE INFORMACAO,TEMPORARIO,20H,SUPERIOR,PLENO
2,3,PROGRAMADOR DE SISTEMAS DE INFORMACAO,TEMPORARIO,20H,POS,SENIOR
3,4,PROGRAMADOR DE SISTEMAS DE INFORMACAO,TEMPORARIO,40H,MEDIO,JUNIOR
4,5,PROGRAMADOR DE SISTEMAS DE INFORMACAO,TEMPORARIO,40H,SUPERIOR,PLENO

In [ ]:
clientePandas=pd.read_csv('https://raw.githubusercontent.com/cristinaaguiar/DataMartBISolutions/main/cliente.csv', sep=',')
clientePandas.head()

,clientePK,clienteNomeFantasia,clienteSetor,clienteCidade,clienteEstadoNome,clienteEstadoSigla,clienteRegiaoNome,clienteRegiaoSigla,clientePaisNome,clientePaisSigla
0,1,VIA FOOD,BEBIDAS E ALIMENTOS,SAO PAULO,SAO PAULO,SP,SUDESTE,SE,BRASIL,BR
1,2,VIA PIZZA,BEBIDAS E ALIMENTOS,SAO PAULO,SAO PAULO,SP,SUDESTE,SE,BRASIL,BR
2,3,VIA JAPA,BEBIDAS E ALIMENTOS,SAO PAULO,SAO PAULO,SP,SUDESTE,SE,BRASIL,BR
3,4,VIA VEG,BEBIDAS E ALIMENTOS,SAO PAULO,SAO PAULO,SP,SUDESTE,SE,BRASIL,BR
4,5,VIA DRINK,BEBIDAS E ALIMENTOS,SAO CARLOS,SAO PAULO,SP,SUDESTE,SE,BRASIL,BR

In [ ]:
dataPandas=pd.read_csv('https://raw.githubusercontent.com/cristinaaguiar/DataMartBISolutions/main/data.csv', sep=',')
dataPandas.head()

,dataPK,dataCompleta,dataDia,dataMes,dataBimestre,dataTrimestre,dataSemestre,dataAno
0,1,1/1/2016,1,1,1,1,1,2016
1,2,2/1/2016,2,1,1,1,1,2016
2,3,3/1/2016,3,1,1,1,1,2016
3,4,4/1/2016,4,1,1,1,1,2016
4,5,5/1/2016,5,1,1,1,1,2016

In [ ]:
equipePandas = pd.read_csv('https://raw.githubusercontent.com/cristinaaguiar/DataMartBISolutions/main/equipe.csv', sep=',')
equipePandas.head()

,equipePK,equipeNome,filialNome,filialCidade,filialEstadoNome,filialEstadoSigla,filialRegiaoNome,filialRegiaoSigla,filialPaisNome,filialPaisSigla
0,1,APP - DESKTOP,SAO PAULO - AV. PAULISTA,SAO PAULO,SAO PAULO,SP,SUDESTE,SE,BRASIL,BR
1,2,APP - DESKTOP,RIO DE JANEIRO - BARRA DA TIJUCA,RIO DE JANEIRO,RIO DE JANEIRO,RJ,SUDESTE,SE,BRASIL,BR
2,3,WEB,SAO PAULO - AV. PAULISTA,SAO PAULO,SAO PAULO,SP,SUDESTE,SE,BRASIL,BR
3,4,WEB,RIO DE JANEIRO - BARRA DA TIJUCA,RIO DE JANEIRO,RIO DE JANEIRO,RJ,SUDESTE,SE,BRASIL,BR
4,5,WEB,CAMPO GRANDE - CENTRO,CAMPO GRANDE,MATO GROSSO DO SUL,MS,CENTRO-OESTE,CO,BRASIL,BR

In [ ]:
funcionarioPandas=pd.read_csv('https://raw.githubusercontent.com/cristinaaguiar/DataMartBISolutions/main/funcionario.csv', sep=',')
funcionarioPandas.head()

,funcPK,funcMatricula,funcNome,funcSexo,funcDataNascimento,funcDiaNascimento,funcMesNascimento,funcAnoNascimento,funcCidade,funcEstadoNome,funcEstadoSigla,funcRegiaoNome,funcRegiaoSigla,funcPaisNome,funcPaisSigla
0,1,M-1,ALINE ALMEIDA,F,1/1/1990,1,1,1990,SAO PAULO,SAO PAULO,SP,SUDESTE,SE,BRASIL,BR
1,2,M-2,ARAO ALVES,M,2/2/1990,2,2,1990,CAMPINAS,SAO PAULO,SP,SUDESTE,SE,BRASIL,BR
2,3,M-3,ARON ANDRADE,M,3/3/1990,3,3,1990,SANTOS,SAO PAULO,SP,SUDESTE,SE,BRASIL,BR
3,4,M-4,ADA BARBOSA,F,4/4/1990,4,4,1990,SANTO ANDRE,SAO PAULO,SP,SUDESTE,SE,BRASIL,BR
4,5,M-5,ABADE BATISTA,M,5/5/1990,5,5,1990,PIRACICABA,SAO PAULO,SP,SUDESTE,SE,BRASIL,BR

In [ ]:
negociacaoPandas=pd.read_csv('https://raw.githubusercontent.com/cristinaaguiar/DataMartBISolutions/main/negociacao.csv')
negociacaoPandas.head()

   equipePK  clientePK  dataPK  receita  quantidadeNegociacoes
0         2          9      22 11564.75                      1
1         2         24      11 17990.50                      1
2         2         28      21 16335.90                      1
3         1         30      23  8495.55                      1
4         2         43      30 24748.75                      1

In [ ]:
pagamentoPandas = pd.read_csv('https://raw.githubusercontent.com/cristinaaguiar/DataMartBISolutions/main/pagamento.csv')
pagamentoPandas.head()

   funcPK  equipePK  dataPK  cargoPK  salario  quantidadeLancamentos
0     147         2       5       64  1559.94                      1
1     124         2       5      329  8102.77                      1
2     175         1       5      328  2532.51                      1
3     171         1       5      245  7882.70                      1
4     148         2       5       65  4404.59                      1